config/routes.rb
MarketResearch::Application.routes.draw do
  resources :mines do
    resources :configurations do
      get 'calc', :on => :member
      resources :configuration_segments, except: :index
    end

    resources :groupings do
      resources :grouping_parameters, :only => [:edit, :update]
      put 'rebuild', :on => :member
      resources :grouping_segments, :only => [:index, :show]
    end
  end

  root :to => 'mines#index'
end

app/models/grouping.rb
# encoding: utf-8

class Grouping < ActiveRecord::Base
  attr_accessible :title, :grouping_parameters_attributes

  belongs_to :mine

  has_many :grouping_parameters, :dependent => :destroy, :order => 'grouping_parameters.id ASC'
  has_many :grouping_segments, :dependent => :destroy

  accepts_nested_attributes_for :grouping_parameters, :allow_destroy => true

  def rebuild_segments
    GroupingSegment.roots.where(:grouping_value_id => grouping_parameters.map(&:grouping_values).flatten).destroy_all
    recalculate_segments
  end

  def recalculate_segments(previous_segment = nil, grouping_parameter = nil, level = 0)
    grouping_parameter ||= grouping_parameters.first
    grouping_parameter.grouping_values.each do |value|
      segment_title = value.title
      segment = GroupingSegment.create! :title => segment_title, :grouping_value => value, :parent => previous_segment, :grouping => self
      recalculate_segments(segment, grouping_parameters[level+1], level+1) if level+1 < grouping_parameters.count
    end
  end

end

app/controllers/groupings_controller.rb
class GroupingsController < ApplicationController
  inherit_resources

  actions :all

  belongs_to :mine

  custom_actions :resource => [:rebuild]

  def rebuild
    resource.rebuild_segments
    redirect_to mine_grouping_grouping_segments_path(parent, resource)
  end
end

app/views/groupings/_form.html.erb
<%= simple_nested_form_for [@mine, @grouping] do |f|  %>
  <%= f.input :title %>

  <%= f.fields_for :grouping_parameters do |parameter_form| %>
    <%= parameter_form.input :title, :as => :select, :collection => @mine.items_options.keys, :selected => parameter_form.object.title %>
    <%= parameter_form.input :kind %>
    <%= parameter_form.link_to_remove 'remove' %>
  <% end %>
  <%= f.link_to_add 'add', :grouping_parameters %>

  <%= f.submit %>
<% end %>

app/views/groupings/_grouping.html.erb
<div>
  <%= link_to grouping.title, mine_grouping_path(@mine, grouping) %>
  <%= link_to 'edit', edit_mine_grouping_path(@mine, grouping) %>
</div>

app/views/groupings/_segments_level.html.erb
<% segment.children.each do |child| %>
  <tr>
    <td><%= content_tag "h#{child.depth+1}", child.title %></td>
    <td><%= link_to "#{child.items.count}", mine_grouping_segments_path(resource.mine, resource, child) %></td>
  </tr>
  <%= render :partial => 'segments_level', :locals => {segment: child} if child.has_children? %>
<% end %>

app/views/groupings/segments.html.erb
<div class='segmets'>
  <table>
    <% Segment.roots.where(:grouping_value_id => resource.grouping_parameters.map(&:grouping_values).flatten).each do |segment| %>
      <tr>
      <td colspan=2><%= content_tag "h#{segment.depth+1}", "#{segment.title}" %>(<%= link_to "#{segment.items.count}", mine_grouping_segments_path(resource.mine, resource, segment) %>)</td>
      </tr>
      <%= render :partial => 'segments_level', :locals => {segment: segment} %>
    <% end %>
  </table>

  <div class='links'>
    <%= link_to "recalculate", rebuild_resource_path, :method => :put %>
    <%= link_to "back", resource_path %>
  </div>
</div>

app/views/groupings/show.html.erb
<div class='groupings'>
  <h1><%= resource.title %></h1>
  <%= render resource.grouping_parameters %>
  <%= link_to "edit", edit_resource_path %>

  <%= link_to "segments", mine_grouping_grouping_segments_path(@mine, @grouping) %>
</div>