config/routes.rb
MarketResearch::Application.routes.draw do
  resources :mines do
    resources :configurations do
      get 'calc', :on => :member
      resources :configuration_segments, except: :index
    end

    resources :groupings do
      resources :grouping_parameters, :only => [:edit, :update]
      put 'rebuild', :on => :member
      resources :grouping_segments, :only => [:index, :show]
    end
  end

  root :to => 'mines#index'
end

app/models/configuration_segment.rb
class ConfigurationSegment < Segment
  attr_accessible :title, :configuration_segment_parameters_attributes

  belongs_to :configuration

  has_many :configuration_segment_parameters, :dependent => :destroy

  accepts_nested_attributes_for :configuration_segment_parameters

  def initialize_segment_parameters
    configuration.configuration_parameters.each do |configuration_parameter|
        configuration_segment_parameters.build :configuration_parameter => configuration_parameter
    end
  end
end

app/controllers/configuration_segments_controller.rb
class ConfigurationSegmentsController < ApplicationController
  inherit_resources

  actions :all

  belongs_to :mine do
    belongs_to :configuration, :optional => true
  end

  def new
    new! { @configuration_segment.initialize_segment_parameters }
  end

  def create
    create! {parent_url}
  end

  def update
    update! {parent_url}
  end

  def destroy
    destroy! {parent_url}
  end
end

app/views/configuration_segments/_configuration_segment.html.erb
<tr>
  <td>
    <%= configuration_segment.title %>
    (<%= link_to "#{configuration_segment.items.count}", mine_configuration_configuration_segment_path(configuration_segment.configuration.mine, configuration_segment.configuration, configuration_segment) %>)
    <%= link_to 'edit', edit_mine_configuration_configuration_segment_path(@mine, @configuration, configuration_segment) %>
    <%= link_to 'delete', mine_configuration_configuration_segment_path(@mine, @configuration, configuration_segment), :method => :delete, :confirm => 'Вы уверены?' %>
  </td>
</tr>

app/views/configuration_segments/_form.html.erb
<%= simple_nested_form_for [@mine, @configuration, @configuration_segment] do |f| %>
  <%= f.input :title %>
  <%= f.fields_for :configuration_segment_parameters do |param_form| %>
    <h3><%= param_form.object.configuration_parameter.title %></h3>
    <%= param_form.input :configuration_parameter_id, :as => :hidden %>

    <% if param_form.object.configuration_parameter.kind.quality? %>
      <%= param_form.input :quality_value,
        :as => :check_boxes,
        :collection => @mine.uniq_values_for_option(param_form.object.configuration_parameter.title) %>
    <% else %>
      <%= param_form.input :quantity_value, :as => :integer %>
    <% end %>
  <% end %>

  <%= f.submit %>
<% end %>

<%= link_to 'back', [@mine, @configuration] %>

app/views/configuration_segments/edit.html.erb
<%= render 'form' %>

app/views/configuration_segments/new.html.erb
<%= render 'form' %>

app/views/configuration_segments/show.html.erb
<h1><%= @configuration_segment.title %></h1>
<h2>Список учреждений</h2>
<table>
  <tr>
    <th>Название</th>
    <th>Адрес</th>
    <th>Телефон</th>
    <th>Email</th>
  </tr>
  <% @configuration_segment.items.each do |item| %>
    <tr>
      <%= render partial: 'items/item', locals: {item: item} %>
    </tr>
  <% end %>
</table>
<%= link_to "back", mine_configuration_path(@configuration_segment.configuration.mine, @configuration_segment.configuration) %>