config/routes.rb
MarketResearch::Application.routes.draw do
  resources :mines do
    resources :configurations do
      get 'calc', :on => :member
      resources :configuration_segments, except: :index
    end

    resources :groupings do
      resources :grouping_parameters, :only => [:edit, :update]
      put 'rebuild', :on => :member
      resources :grouping_segments, :only => [:index, :show]
    end
  end

  root :to => 'mines#index'
end

app/models/configuration.rb
class Configuration < ActiveRecord::Base
  attr_accessible :title, :configuration_parameters_attributes

  belongs_to :mine

  has_many :configuration_parameters, :dependent => :destroy, :order => 'configuration_parameters.id ASC'
  has_many :items,                    :through => :mine

  has_many :configuration_segments,   :dependent => :destroy, :order => 'id ASC'
  has_many :configuration_segment_parameters,       :through => :configuration_segments
  has_many :item_segments,            :through => :configuration_segments

  accepts_nested_attributes_for :configuration_parameters

  def calc
    set_min_and_max_values_for_quantity_parameters
    delete_item_segments

    items.each do |item|
      closest_segment = configuration_segments.first
      min_dist = item.dist_from(closest_segment)

      configuration_segments[1..-1].each do |segment|
        dist = item.dist_from(segment)
        if dist < min_dist
          min_dist = dist
          closest_segment = segment
        end
      end

      closest_segment.item_segments.create :item_id => item.id, :distance => min_dist
    end
  end

  private

  def set_min_and_max_values_for_quantity_parameters
    configuration_parameters.where(:kind => :quantity).map(&:set_min_and_max_value)
  end

  def delete_item_segments
    configuration_segments.each { |segment| segment.item_segments.destroy_all }
  end
end

app/controllers/configurations_controller.rb
class ConfigurationsController < ApplicationController
  inherit_resources

  belongs_to :mine

  custom_actions :resource => :calc

  def calc
    calc! {
      @configuration.calc
      redirect_to [@mine, @configuration] and return
    }
  end
end

app/views/configurations/_configuration.html.erb
<div>
  <%= link_to "#{configuration.title}", mine_configuration_path(@mine, configuration) %>
  <%= link_to "edit", edit_mine_configuration_path(@mine, configuration)  %>
</div>

app/views/configurations/_form.html.erb
<%= simple_nested_form_for [parent, resource] do |f| %>
  <%= f.input :title %>
  <%= f.fields_for :configuration_parameters do |ff| %>
    <%= ff.input :title, :collection => parent.items_options.keys %>
    <%= ff.input :kind %>
    <%= ff.input :weight %>
    <%= ff.link_to_remove 'remove' %>
  <% end %>
  <%= f.link_to_add 'add', :configuration_parameters %>
  <%= f.submit %>
<% end %>

app/views/configurations/show.html.erb
<%= @configuration.title %>

<%= render @configuration.configuration_parameters %>

<%= link_to 'new segment', new_mine_configuration_configuration_segment_path(@mine, @configuration) %>

<%= link_to 'calc', calc_mine_configuration_path(@mine, @configuration) %>

<table>
  <%= render @configuration.configuration_segments %>
</table>

<div class="cloud cluster" data-json='<%= JSON.pretty_generate(@configuration.item_segments.as_json) %>' data-segments='<%= @configuration.configuration_segments.count %>'></div>