config/routes.rb
MarketResearch::Application.routes.draw do
  resources :mines do
    resources :configurations do
      get 'calc', :on => :member
      resources :configuration_segments, except: :index
    end

    resources :groupings do
      resources :grouping_parameters, :only => [:edit, :update]
      put 'rebuild', :on => :member
      resources :grouping_segments, :only => [:index, :show]
    end
  end

  root :to => 'mines#index'
end

app/models/grouping_segment.rb
require 'segment'

class GroupingSegment < Segment
  has_ancestry

  attr_accessible :title, :grouping_value, :parent, :grouping

  belongs_to :grouping

  belongs_to :grouping_value, :polymorphic => true

  after_create :associate_items

  private

  def associate_items
    (parent || grouping_value.grouping_parameter.grouping.mine).items.each do |item|
      item_parameter_value = item.data[grouping_value.grouping_parameter.title]
      case grouping_value.class.name
      when  "QualityGroupingValue"
        item_segments.create(item_id: item.id) if grouping_value.values.include?(item_parameter_value)
      when "QuantityGroupingValue"
        item_parameter_value = item_parameter_value.to_i
        item_segments.create(item_id: item.id) if item_parameter_value >= grouping_value.min_count && item_parameter_value <= grouping_value.max_count
      end
    end
  end
end

app/controllers/grouping_segments_controller.rb
class GroupingSegmentsController < ApplicationController
  inherit_resources

  actions :all, :only => [:show]

  belongs_to :mine do
    belongs_to :grouping
  end

  protected
  def collection
    @segments ||= GroupingSegment.roots.where(:grouping_id => parent.id).order(:title)
  end

end

app/views/grouping_segments/_segments_level.html.erb
<% segment.children.order(:title).each do |child| %>
  <tr>
    <td><%= content_tag "h#{child.depth+1}", child.title %></td>
    <td><%= link_to "#{child.items.count}", [@mine, @grouping, child] %></td>
  </tr>
  <%= render :partial => 'segments_level', :locals => {segment: child} if child.has_children? %>
<% end %>

app/views/grouping_segments/index.html.erb
<div class='segmets'>
  <table>
    <% collection.each do |segment| %>
      <tr>
      <td colspan=2><%= content_tag "h#{segment.depth+1}", "#{segment.title}" %>(<%= link_to "#{segment.items.count}", [@mine, @grouping, segment] %>)</td>
      </tr>
      <%= render :partial => 'segments_level', :locals => {segment: segment} %>
    <% end %>
  </table>

  <div class='links'>
    <%= link_to "recalculate", rebuild_mine_grouping_path(@mine, @grouping), :method => :put %>
    <%= link_to "back", [@mine, @grouping] %>
  </div>
</div>

app/views/grouping_segments/show.html.erb
<h1>
  <% @grouping_segment.ancestors.each do |ancestor| %>
    <%= ancestor.title %>
  <% end %>
  <%= @grouping_segment.title %>
</h1>
<h2>Список учреждений</h2>
<table>
  <tr>
    <th>Название</th>
    <th>Адрес</th>
    <th>Телефон</th>
    <th>Email</th>
  </tr>
  <% @grouping_segment.items.each do |item| %>
    <tr>
      <%= render partial: 'items/item', locals: {item: item} %>
    </tr>
  <% end %>
</table>
<%= link_to "back", mine_grouping_grouping_segments_path(@mine, @grouping) %>